spring:
    application:
        name: lovemybike
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:bikes;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        platform: h2
    h2:
        console:
            enabled: true
            path: /console

    jpa.hibernate.ddl-auto: none

multipart:
    max-file-size: 5MB
    max-request-size: 100MB

server:
    port: 9000