spring:
    application:
        name: lovemybike
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        platform: h2
    h2:
        console:
            enabled: true
            path: /console
server:
    port: 9000