spring:
    application:
        name: lovemybike
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:bikes;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        platform: h2
    h2:
        console:
            enabled: true
            path: /console

    jpa.hibernate.ddl-auto: none
    http.multipart:
        max-file-size: 6MB
        max-request-size: 100MB

aws:
    s3AccessKey: AKIAJXV23NQFIODDAROQ
    s3SecretKey: 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
    s3Bucket: bike-bucket

server:
    port: 9000